spring:
  datasource:
    url: jdbc:postgresql:pharmagator
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate

pharmagator:
  data-providers:
    apteka-rozetka:
      url: https://xl-catalog-api.rozetka.com.ua/v4/goods
      medicines-fetch-url: /getDetails
      ids-fetch-url: /get
      category-id: !!str 4628621
      sell-status: available

